//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int BillID { get; set; }
        public int OrderDetailID { get; set; }
        public int UserID { get; set; }
        public int CustomerID { get; set; }
        public decimal TotalAmount { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public string PaymentStatus { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual OrderDetail OrderDetail { get; set; }
        public virtual User User { get; set; }
    }
}
