//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProvideDetail
    {
        public int ProvideDetailID { get; set; }
        public Nullable<int> ProviderID { get; set; }
        public Nullable<int> IngredientID { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
    
        public virtual Ingredient Ingredient { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
