//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProviderOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProviderOrder()
        {
            this.ProviderOrderDetails = new HashSet<ProviderOrderDetail>();
        }
    
        public int ProviderOrderID { get; set; }
        public int ProviderID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public Nullable<System.DateTime> ExpectedDeliveryDate { get; set; }
        public string Status { get; set; }
    
        public virtual Provider Provider { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProviderOrderDetail> ProviderOrderDetails { get; set; }
    }
}
