//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProviderOrderDetail
    {
        public int ProviderOrderDetailID { get; set; }
        public int ProviderOrderID { get; set; }
        public int IngredientID { get; set; }
        public decimal Quantity { get; set; }
        public decimal Price { get; set; }
    
        public virtual Ingredient Ingredient { get; set; }
        public virtual ProviderOrder ProviderOrder { get; set; }
    }
}
