//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProvideDetail
    {
        public string ProvideDetailID { get; set; }
        public string ProviderID { get; set; }
        public string IngredientID { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
    
        public virtual Ingredient Ingredient { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
